#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import JointState

if __name__ == "__main__":
 # Declarar el nombre del nodo
 rospy.init_node("JointsNode")
 
 # Definir el publicador
 
 
 # Definir una variable de tipo JointState
 
 
 # Definir las propiedades de la variable JointState
 # - Definir el tiempo en el stamp

 # - Definir los nombres de la articulacion como una lista

 # - Definir las posiciones articulares como una lista
 
 # Definir un bucle y su tiempo de muestreo, dentro del bucle, publicar el mensaje
