#!/usr/bin/env python3

import rospy
from std_msgs.msg import Float64

if __name__ == "__main__":
 # Inicializar e indicar el nombre del nodo
 rospy.init_node("Alexander")
 
 # Definir el publicador para los topicos: /robot/joint1_position_controller/command y /robot/joint2_position_controller/command
 # Se puede revisar el tipo de mensaje que usa el topico, con el comando: $ rostopic info <nombre_topico>
 
 
 # Definir una variable de tipo
 
 
 # Definir las propiedades de la variable
 
 
 # Definir la logica del codigo para que se mueva de una posicion a otra
